M48
; DRILL file {KiCad (7.0.0)} date Tue Feb 28 12:44:18 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-28T12:44:18+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X5.08Y69.85
X5.08Y3.835
X93.98Y69.85
X93.98Y3.81
T0
M30
